### ISSUE TITLE
Convert use of KML to WKT

### ISSUE THREAD

**Issue by drotheram** [Volcano-Risk-Reduction-in-Canada/eodms-cli#1]
- Convert KML polygons to WKT
- Standardize volcano site names to harmonize with orderFreshRCMImagery.sh
       - Example: `A4202_Volcano_Garbld.kml` should be expanded to `A4202_Volcano_Garibaldi.wkt`
- Consider ways to reduce code replication in orderFreshRCMImagery.sh

**Comment by trbeattie** [comment]
I think this one can be marked as done finally, as I believe the implementation of the AOIs in GeoJSON through the VRRC API essentially covers this. I'd close it but don't seem to have the ability to close issues for this project.

**Comment by drotheram** [comment]
the cli code is still using kml. Since we will be moving to VRRC-API I think we can close with a 'Closed as not planned'

**Comment by drotheram** [comment]
Entire eodms-cli will be depricated by VRRC-API
