### ISSUE TITLE
createImageSqs.py bug, not correctly parsing referenceDate in for some site/beam combinations

### ISSUE THREAD

**Issue by drotheram** [Volcano-Risk-Reduction-in-Canada/eodms-cli#2]
```
`    rawImages = s3.list_objects_v2(Bucket='vrrc-rcm-raw-data-store', 
                             Prefix='{}/{}/'.format(args.site, args.beam), 
                             Delimiter="/")

```
```
    refdateList=[]
    for date in rawImages['Contents']:
        refdateList.append(date['Key'].split('_')[5])
`
```

date parsing splits on '_' however this breaks for sites that contain underscore in the name such as:
Edziza_South, Edziza_North & Lava_Fork

**Comment by drotheram** [comment]
S3 URI's format example:
s3://vrrc-rcm-raw-data-store/Edziza_South/3M31/RCM1_OK2042971_PK2171297_1_3M31_20220719_145359_HH_SLC.zip

**Comment by drotheram** [comment]
S3 URI example which does not produce bug:
s3://vrrc-rcm-raw-data-store/Garibaldi/3M23/RCM1_OK2042935_PK2150963_1_3M23_20220703_142352_HH_SLC.zip

**Comment by trbeattie** [comment]
Can't test this myself in the AWS environment yet, but an extra 'split' to separate out the base filename from the rest of the path should do the trick as long as the base filename format remains consistent:

```
    for date in rawImages['Contents']:
        basename = date['Key'].split('/')[-1] # basename = 'RCM1_OK2042971_PK2171297_1_3M31_20220719_145359_HH_SLC.zip'
        refdate = basename.split('_')[5] # refdate = '20220719'
        refdateList.append(refdate)
```

**Comment by drotheram** [comment]
That should do it

**Comment by drotheram** [comment]
fixed by https://github.com/Volcano-Risk-Reduction-in-Canada/eodms-cli/commit/1066cdb9a3fb0db727b07c0e5106cd62db84c13b with credit to @trbeattie
